# Student Performance Factors

The short notebook will perform the following:

1. Statistical analysis - Z-test/T-test, ANOVA, Goodness of Fit, etc.

2. Two (2) machine learning algorithms for the prediction of the target variable:
    - One based on exploratory analysis of data for consistent pattern prediction
    - One based on external/real-world trends

## About the Data

It contains information on each student's study habits, motivation level, family history, attendance at school, and availability of learning materials. Lifestyle characteristics including physical activity, sleep duration, and involvement in extracurricular activities are also recorded in the dataset. Combining these factors gives the file a thorough understanding of how many social, educational, and personal factors affect the students' final exam results.

| **Column Name**            | **Description**                                                                 | **Data Type** |
| -------------------------- | ------------------------------------------------------------------------------- | ------------- |
| Hours_Studied              | Number of hours a student studies per week.                                     | Integer       |
| Attendance                 | Percentage of school attendance.                                                | Integer       |
| Parental_Involvement       | Level of parents’ participation in the student’s education (Low, Medium, High). | Categorical   |
| Access_to_Resources        | Availability of learning materials and digital tools (Low, Medium, High).       | Categorical   |
| Extracurricular_Activities | Whether the student participates in extracurricular activities (Yes/No).        | Categorical   |
| Sleep_Hours                | Average hours of sleep per day.                                                 | Integer       |
| Previous_Scores            | Average marks or grades from previous assessments.                              | Integer       |
| Motivation_Level           | Student’s motivation level toward studies (Low, Medium, High).                  | Categorical   |
| Internet_Access            | Whether the student has internet access at home (Yes/No).                       | Categorical   |
| Tutoring_Sessions          | Number of extra tutoring or coaching sessions attended per week.                | Integer       |
| Family_Income              | Economic status of the student’s family (Low, Medium, High).                    | Categorical   |
| Teacher_Quality            | Quality of instruction received from teachers (Low, Medium, High).              | Categorical   |
| School_Type                | Type of educational institution (Public/Private).                               | Categorical   |
| Peer_Influence             | Nature of peer influence (Positive, Neutral, Negative).                         | Categorical   |
| Physical_Activity          | Number of physical activity sessions per week.                                  | Integer       |
| Learning_Disabilities      | Indicates if the student has a learning disability (Yes/No).                    | Categorical   |
| Parental_Education_Level   | Highest education level of parents (High School, College, Postgraduate).        | Categorical   |
| Distance_from_Home         | Distance between student’s home and school (Near, Moderate, Far).               | Categorical   |
| Gender                     | Student’s gender (Male/Female).                                                 | Categorical   |
| Exam_Score                 | Final exam score or academic performance (**target variable**).                 | Integer       |

# Exploratory Analysis

In [ ]:
from data_tools.data_import.kaggle import download_data

# Download latest version
download_data("mosapabdelghany/student-performance-factors-dataset")

/run/media/toni11/fedora01/home01/Programming_Projects/Data_Science_Projects/Short_projects/Project1-Student_Statistics

(False,
 'Unexpected error: expected str, bytes or os.PathLike object, not CompletedProcess')

In [50]:
import pandas as pd
import numpy as np

def explore(df):
    """Descriptive and exploratory analysis

    Args:
        df (pd.DataFrame): DataFrame to analyze
    """
    print("Head of dataset: ")
    display(df.head(5))
    
    print("Dataset information")
    display(df.info())
    
    print("Describe")
    display(df.describe())

def check_unqiue(df):
    """Check unqiue values and count null values for each columns

    Args:
        df (pd.DataFrame): DataFrame to analyze
    """
    null_cols = []
    for col in df.columns:
        print(f"Column {col}:")
        null_count = df[col].isna().sum()
        if null_count > 0:
            print(f"Null count: {null_count}\n")
            null_cols.append(col)
        else:
            print("\n")
            
        if df[col].dtype == "object":
            print(f"Unqiue values: {df[col].unique()} \n")
        else:
            print("\n")
    
    print(f"Null columns: {null_cols}")

In [51]:
data_path = "StudentPerformanceFactors.csv"
data = pd.read_csv(data_path)

explore(data)
check_unqiue(data)

Head of dataset:

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

Dataset information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

None

Describe

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

Column Hours_Studied:




Column Attendance:




Column Parental_Involvement:


Unqiue values: ['Low' 'Medium' 'High']

Column Access_to_Resources:


Unqiue values: ['High' 'Medium' 'Low']

Column Extracurricular_Activities:


Unqiue values: ['No' 'Yes']

Column Sleep_Hours:




Column Previous_Scores:




Column Motivation_Level:


Unqiue values: ['Low' 'Medium' 'High']

Column Internet_Access:


Unqiue values: ['Yes' 'No']

Column Tutoring_Sessions:




Column Family_Income:


Unqiue values: ['Low' 'Medium' 'High']

Column Teacher_Quality:
Null count: 78

Unqiue values: ['Medium' 'High' 'Low' nan]

Column School_Type:


Unqiue values: ['Public' 'Private']

Column Peer_Influence:


Unqiue values: ['Positive' 'Negative' 'Neutral']

Column Physical_Activity:




Column Learning_Disabilities:


Unqiue values: ['No' 'Yes']

Column Parental_Education_Level:
Null count: 90

Unqiue values: ['High School' 'College' 'Postgraduate' nan]

Column Distance_from_Home:
Null count: 67

Unqiue values: ['Near' 'Moderate' 'Far' nan]

Column Gender:


Unqiue values: ['Male' 'Female']

Column Exam_Score:




Null columns: ['Teacher_Quality', 'Parental_Education_Level', 'Distance_from_Home']

## Statistical Treatment

### Questions 

- What factors from the 18 listed affects the exam scores the most?

- Which factors have medium to high correlation with each other in such that they can be combined as one feature with each other, given the possibility of combining the features?

- How does the Goodness of Fit influence the model that will be developed based on the pattern?

In [53]:
# We'll start with a correlation matrix

corr_matrix = data.corr(method='spearman',min_periods=1000,numeric_only=True)
display(corr_matrix)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
Hours_Studied,1.000000,-0.009814,0.011187,0.024106,-0.012922,-0.002647,0.480956
Attendance,-0.009814,1.000000,-0.012636,-0.020064,0.014771,-0.024181,0.672366
Sleep_Hours,0.011187,-0.012636,1.000000,-0.022292,-0.006139,0.000871,-0.007629
Previous_Scores,0.024106,-0.020064,-0.022292,1.000000,-0.018188,-0.008226,0.191941
Tutoring_Sessions,-0.012922,0.014771,-0.006139,-0.018188,1.000000,0.007509,0.163940
Physical_Activity,-0.002647,-0.024181,0.000871,-0.008226,0.007509,1.000000,0.029150
Exam_Score,0.480956,0.672366,-0.007629,0.191941,0.163940,0.029150,1.000000